spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login
    username: organic
    password: organic

mybatis:
  mapper-locations: mapper/**/*.xml
